spring:
  application:
    name: news-platform
  profiles:
    active: dev
  
  datasource:
    # Autorise soit SPRING_DATASOURCE_URL (fourni par Render) soit la construction manuelle via DB_*.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:newsplatform}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:admin_9F8a7C}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:G7!pR2@vLq8z}}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    # Hérite par défaut de datasource mais permet la surcharge via SPRING_FLYWAY_* si nécessaire.
    url: ${SPRING_FLYWAY_URL:${spring.datasource.url}}
    user: ${SPRING_FLYWAY_USER:${spring.datasource.username}}
    password: ${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

jwt:
  secret: ${JWT_SECRET:Qw3rT6yU9oP2sV5bX8cZ1aL4dE7gH0jK}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

logging:
  level:
    com.newsplatform: DEBUG
    org.springframework.security: DEBUG 